# -*- coding: utf-8 -*-
"""Module 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REsjvsdulk4VPThbei2VXhS_as2e6eEh
"""

import pandas as pd
import matplotlib.pyplot as plt


file_path = "Jets data 2010-2025.xlsx"
raw_df = pd.read_excel(file_path)


raw_df.columns = raw_df.iloc[0]
df = raw_df[1:].copy()


df = df.rename(columns={
    'Year': 'season',
    'Lg': 'league',
    'Tm': 'team',
    'W': 'wins',
    'L': 'losses',
    'T': 'ties',
    'Div. Finish': 'division_finish',
    'Playoffs': 'playoffs',
    'PF': 'points_for',
    'PA': 'points_against',
    'PD': 'point_diff',
    'Coaches': 'coach',
    'AV': 'top_player_av',
    'Passer': 'top_passer',
    'Rusher': 'top_rusher',
    'Receiver': 'top_receiver',
    'Pts': 'off_rank_pts',
    'Yds': 'off_rank_yds',
    'T/G': 'overall_rank_tg',
    'Pts±': 'overall_rank_pts_pm',
    'Yds±': 'overall_rank_yds_pm',
    'out of': 'teams_in_league',
    'MoV': 'margin_of_victory',
    'SoS': 'strength_of_schedule',
    'SRS': 'srs',
    'OSRS': 'osrs',
    'DSRS': 'dsrs'
})


df.columns = [
    'season', 'league', 'team', 'wins', 'losses', 'ties',
    'division_finish', 'playoffs',
    'points_for', 'points_against', 'point_diff',
    'coach',
    'top_player_av', 'top_passer', 'top_rusher', 'top_receiver',
    'off_rank_pts', 'off_rank_yds',
    'def_rank_pts', 'def_rank_yds',
    'overall_rank_tg', 'overall_rank_pts_pm', 'overall_rank_yds_pm', 'teams_in_league',
    'margin_of_victory', 'strength_of_schedule', 'srs', 'osrs', 'dsrs'
]


numeric_cols = [
    'season', 'wins', 'losses', 'ties',
    'points_for', 'points_against', 'point_diff',
    'off_rank_pts', 'off_rank_yds',
    'def_rank_pts', 'def_rank_yds',
    'overall_rank_tg', 'overall_rank_pts_pm', 'overall_rank_yds_pm',
    'teams_in_league', 'margin_of_victory',
    'strength_of_schedule', 'srs', 'osrs', 'dsrs'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')


df = df.sort_values('season').reset_index(drop=True)


analysis_df = df.copy()


print(analysis_df.head())
print(analysis_df.info())
print(analysis_df.describe())

plt.figure(figsize=(10, 5))
plt.plot(analysis_df['season'], analysis_df['wins'], marker='o')
plt.title('New York Jets Wins by Season')
plt.xlabel('Season')
plt.ylabel('Wins')
plt.xticks(analysis_df['season'], rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
plt.plot(analysis_df['season'], analysis_df['points_for'], marker='o', label='Points Scored')
plt.plot(analysis_df['season'], analysis_df['points_against'], marker='o', label='Points Allowed')
plt.title('Jets Points Scored vs Points Allowed by Season')
plt.xlabel('Season')
plt.ylabel('Points')
plt.xticks(analysis_df['season'], rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
plt.plot(analysis_df['season'], analysis_df['off_rank_pts'], marker='o', label='Offensive Rank (Points)')
plt.plot(analysis_df['season'], analysis_df['def_rank_pts'], marker='o', label='Defensive Rank (Points Allowed)')
plt.gca().invert_yaxis()
plt.title('Jets Offensive vs Defensive Ranking by Season')
plt.xlabel('Season')
plt.ylabel('League Rank (lower is better)')
plt.xticks(analysis_df['season'], rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
plt.scatter(analysis_df['srs'], analysis_df['wins'])
plt.title('Jets Wins vs SRS')
plt.xlabel('SRS')
plt.ylabel('Wins')
plt.tight_layout()
plt.show()

summary_stats = analysis_df[[
    'wins', 'losses', 'points_for', 'points_against',
    'off_rank_pts', 'def_rank_pts', 'srs'
]].describe()

print(summary_stats)