# -*- coding: utf-8 -*-
"""Module 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CSiCtjl2W6v30FTC-dzciUz4-2e5NqdH
"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt

per_game = pd.read_csv("nba_2025_per_game.csv")
advanced = pd.read_csv("nba_2025_advanced.csv")
print(per_game.columns.tolist())
print(advanced.columns.tolist())

per_game = per_game[per_game["Player"] != "Player"].copy()
advanced = advanced[advanced["Player"] != "Player"].copy()

per_game = per_game[[
    "Player", "Team", "Pos", "Age", "G", "GS", "MP",
    "PTS", "AST", "TRB", "FG%", "3P%"
]].copy()

advanced = advanced[[
    "Player", "Team", "PER", "TS%", "USG%", "WS", "BPM", "VORP"
]].copy()
df = pd.merge(per_game, advanced, on=["Player", "Team"], how="inner")
print(df.head())
print(df.shape)

df = df[(df["MP"] >= 20) & (df["G"] >= 40)].copy()
print(df.shape)

features = ["PTS", "AST", "TRB", "FG%", "3P%", "PER", "TS%", "USG%", "BPM"]

df_model = df[["Player", "Team", "Pos"] + features].dropna().copy()
query_players = ["Stephen Curry", "LeBron James", "Nikola Jokić"]
print(df_model[df_model["Player"].isin(query_players)][["Player", "Team", "Pos"]])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_model[features])
similarity_matrix = cosine_similarity(X_scaled)

def top_similar_players(player_name, df_players, sim_matrix, top_n=10):
    matches = df_players.index[df_players["Player"] == player_name].tolist()

    if not matches:
        raise ValueError(f"{player_name} not found in dataset.")

    idx = matches[0]
    sim_scores = list(enumerate(sim_matrix[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    results = []
    for i, score in sim_scores:
        similar_player = df_players.iloc[i]["Player"]
        team = df_players.iloc[i]["Team"]
        pos = df_players.iloc[i]["Pos"]

        if similar_player != player_name:
            results.append((similar_player, team, pos, score))

        if len(results) == top_n:
            break

    return pd.DataFrame(results, columns=["Player", "Team", "Pos", "Cosine Similarity"])

curry_top10 = top_similar_players("Stephen Curry", df_model, similarity_matrix, top_n=10)
lebron_top10 = top_similar_players("LeBron James", df_model, similarity_matrix, top_n=10)
jokic_top10 = top_similar_players("Nikola Jokić", df_model, similarity_matrix, top_n=10)

print("Top 10 players most similar to Stephen Curry:")
print(curry_top10)

print("\nTop 10 players most similar to LeBron James:")
print(lebron_top10)

print("\nTop 10 players most similar to Nikola Jokic:")
print(jokic_top10)

plt.figure(figsize=(10, 6))
plt.barh(curry_top10["Player"][::-1], curry_top10["Cosine Similarity"][::-1])
plt.xlabel("Cosine Similarity")
plt.title("Top 10 Most Similar Players to Stephen Curry (2024-25)")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.barh(lebron_top10["Player"][::-1], lebron_top10["Cosine Similarity"][::-1])
plt.xlabel("Cosine Similarity")
plt.title("Top 10 Most Similar Players to LeBron James (2024-25)")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.barh(jokic_top10["Player"][::-1], jokic_top10["Cosine Similarity"][::-1])
plt.xlabel("Cosine Similarity")
plt.title("Top 10 Most Similar Players to Nikola Jokic (2024-25)")
plt.tight_layout()
plt.show()