# -*- coding: utf-8 -*-
"""Module 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zn5fz4SfV7oEgpCLVESVlik7_RnF_aTa
"""

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt


match_id = 18236

url = f"https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/{match_id}.json"
events = pd.read_json(url)

events.head()

events.columns.tolist()

passes = events[events["type"].apply(lambda x: x.get("name") if isinstance(x, dict) else None) == "Pass"].copy()

passes.head()

passes["passer"] = passes["player"].apply(lambda x: x.get("name") if isinstance(x, dict) else None)
passes["receiver"] = passes["pass"].apply(
    lambda x: x.get("recipient", {}).get("name") if isinstance(x, dict) else None
)

passes[["passer", "receiver"]].head(10)

passes["team_name"] = passes["team"].apply(lambda x: x.get("name") if isinstance(x, dict) else None)

passes["team_name"].value_counts()

team_name = "Barcelona"
team_passes = passes[passes["team_name"] == team_name].copy()

edge_df = (
    team_passes.groupby(["passer", "receiver"])
    .size()
    .reset_index(name="pass_count")
    .dropna()
)

edge_df.head(10)

G = nx.DiGraph()

for _, row in edge_df.iterrows():
    G.add_edge(row["passer"], row["receiver"], weight=row["pass_count"])

print("Nodes:", G.number_of_nodes())
print("Edges:", G.number_of_edges())

weighted_degree = dict(G.degree(weight="weight"))
sorted_weighted_degree = sorted(weighted_degree.items(), key=lambda x: x[1], reverse=True)

sorted_weighted_degree[:10]

plt.figure(figsize=(12, 8))

pos = nx.spring_layout(G, seed=42)

node_sizes = [weighted_degree[node] * 20 for node in G.nodes()]
edge_widths = [G[u][v]["weight"] / 2 for u, v in G.edges()]

nx.draw_networkx_nodes(G, pos, node_size=node_sizes, alpha=0.8)
nx.draw_networkx_edges(G, pos, width=edge_widths, alpha=0.4, arrows=True)
nx.draw_networkx_labels(G, pos, font_size=10)

plt.title(f"{team_name} Passing Network")
plt.axis("off")
plt.show()